### ISSUE TITLE
Softmax with _HARD_SIGMA

### ISSUE THREAD

**Issue by ktrojanowski-tcl** [fab-jul/imgcomp-cvpr#10]
In quantizer.py (line 82), there are two softmax usages over distances. I wonder if there is any special meaning to phi_hard softmax. 

I would say that argmax could have been done directly on distances, but I might be missing something here.

**Comment by fab-jul** [comment]
That's true! I discovered this a bit late and didn't want to take it out due to not being 100% sure that it would not slightly alter the training dynamics :)

**Comment by ktrojanowski-tcl** [comment]
Thank you for quick answer :)
