### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by geekLR** [fab-jul/imgcomp-cvpr#18]
In the plot chapter，how can we get the *.csv files

**Comment by fab-jul** [comment]
Which chapter are you referring to?

**Comment by RainbowLLL** [comment]
The data used for plotting the rate-distortion curve is given in the plotter.py file. 
Could I know if these data was obtained by training the model at different configs,  and how can we get these different configs or all the pre-trained model at different configs? Thanks in advance!

**Comment by fab-jul** [comment]
Ah I see. The figure and the table were obtained by training 7 different models for different operating points (see paper, "To obtain models for different bitrates, we adapt the target bitrate t and the number of channels K"). We released 3 of these models. But the plotting ocde (`plotter.py` can in theory take any combination of models and dataset.

**Comment by RainbowLLL** [comment]
But there are 28 pair of (bpp, MS-SSIM) data used in plotter.py, how can we get these datas from only 7 different models?

**Comment by fab-jul** [comment]
The curve is using the interpolation code in [plotter.py Line 111](https://github.com/fab-jul/imgcomp-cvpr/blob/86c9c91b625e7c5fa39818ad88a63a0f3d805245/code/plotter.py#L111). Did you train the models?

**Comment by RainbowLLL** [comment]
I read the code in plotter.py and plotted the curve successfully! Thanks a lot!
