### ISSUE TITLE
bpp comparison

### ISSUE THREAD

**Issue by wang-zm18** [fab-jul/imgcomp-cvpr#21]
I want to compare the bpp between real value and estimated value, and I put the Kodak dataset named 'kodak' under the folder "code/ckpts",  why I use the command "python val.py ../ckpts 0515_1103 ../ckpts/kodak --save_ours --real_bpp", I cannot see any results unless "***All given job_ids validated"?. Is there something wrong?

**Comment by fab-jul** [comment]
Hm, did you try without `--real_bpp`? Did you try putting kodak in the same folder as `val.py`?

**Comment by qbzhu2020** [comment]
@wang-zm18 Excuse me! have you solved your problem?If you do, could you tell me how you solved it?

**Comment by fab-jul** [comment]
Will close this due to a lack of activity, please feel free to open with more details.
