### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by qbzhu2020** [fab-jul/imgcomp-cvpr#22]
I just did all as the README said,but when I run the test code:**val.py** like this: **python val.py ../ckpts 0515_1103 ./Kodak --save_ours**.A error occurs like this:
![image](https://user-images.githubusercontent.com/65826012/83599427-b519bc80-a59e-11ea-806e-b0a93a6fd932.png)

**Comment by fab-jul** [comment]
replace `../ckts` with `..`

**Comment by qbzhu2020** [comment]
I‘m sorry!I did just as your advice said,but the error still exist:
![image](https://user-images.githubusercontent.com/65826012/83619057-e786e200-a5bd-11ea-9bdf-7a1704c212cb.png)
here is The directory structure of the code:
![image](https://user-images.githubusercontent.com/65826012/83619318-4b110f80-a5be-11ea-8f39-3c18a75fb0e1.png)
I wonder whether the error is related to the directory stucture.Hoping for your reply!Thank you!
