### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by qbzhu2020** [fab-jul/imgcomp-cvpr#23]
I‘m sorry!I did just as your advice said,but the error still exist:
![1](https://user-images.githubusercontent.com/65826012/83653748-becb1080-a5ee-11ea-9f22-17441cfc29a0.png)
here is The directory structure of the code:
![2](https://user-images.githubusercontent.com/65826012/83653881-e91cce00-a5ee-11ea-8284-d378545796aa.png)
I wonder whether the error is related to the directory stucture.Hoping for your reply!

**Comment by fab-jul** [comment]
Well :) if you run from `.`, you need to pass only `ckpts`

**Comment by qbzhu2020** [comment]
Hmmmm... I tried it again, but it didn't work, either.

**Comment by fab-jul** [comment]
what's the error

**Comment by qbzhu2020** [comment]
Oh......I redownload the code and then the conmmand run successfully！I am so sorry to bother you.Thanks for your patient reply!
