### ISSUE TITLE
log_dir_root

### ISSUE THREAD

**Issue by qbzhu2020** [fab-jul/imgcomp-cvpr#24]
I don't the meaning of "log_dir_root" in the training process

**Comment by fab-jul** [comment]
Please be more specific

**Comment by qbzhu2020** [comment]
I mean the command used in the training process:
![111](https://user-images.githubusercontent.com/65826012/83730797-2c714e00-a67c-11ea-8312-76f16aa6c052.png)

**Comment by fab-jul** [comment]
aha, I see. this is just a random folder where you want training logs to go. for example, you can just pass `logs`

**Comment by qbzhu2020** [comment]
Oh,I know!Thank you!
