### ISSUE TITLE
CodecDistance

### ISSUE THREAD

**Issue by qbzhu2020** [fab-jul/imgcomp-cvpr#26]
Sorry to bother you again!but a warming appers when I am train a model using ImageNet :

**Comment by qbzhu2020** [comment]
**Cannot compute CodecDistance: No matches in other_codecs/out_bpg_imagenet_256_train_val_128x128__100**

**Comment by fab-jul** [comment]
What command are your running

**Comment by qbzhu2020** [comment]
Thank you for your reply!My command is:   
 python train.py ae_configs/cvpr/hi pc_configs/cvpr/res_shallow \
            --dataset_train imgnet_train \
            --dataset_test imgnet_test \
            --log_dir_root ./log

**Comment by qbzhu2020** [comment]
and yesterday  when i created records just as your README says，another error occurs：
**Memory Error**
![22](https://user-images.githubusercontent.com/65826012/84029843-a3cd1780-a9c5-11ea-93c5-32db0dcbddb7.png)
but at last the process is finished 100%,i am confused whether it matters
