### ISSUE TITLE
inference using real_bpp

### ISSUE THREAD

**Issue by madisa1** [fab-jul/imgcomp-cvpr#29]
Hello!

When I run val.py and I pass --real_bpp, I got an error "Expected bpp_theory to match loss! ". I can't understand why ? bpp_real and bpp_theory are equal. You can see the results in the pic below.

Thank you.

![Capture](https://user-images.githubusercontent.com/29478246/85124687-9c5e0780-b22a-11ea-8933-6fc67f8ecd92.PNG)

**Comment by madisa1** [comment]
@fab-jul

**Comment by fab-jul** [comment]
hm this is a massive gap. can you provide some more details as to where this compes from? e.g. an image.
