### ISSUE TITLE
how to train a lower bit rate model

### ISSUE THREAD

**Issue by FanYanqi** [fab-jul/imgcomp-cvpr#3]
Excuse me. I'm confused with the configurations of training part.
I want to train a lower bit rate model such as bpp 0.2 or lower.
I used the `ae_configs/cvpr/low` directly or modified it by `H_target = 2*0.1`.
But after about 200000 iterations the average bpp of models on Kodak dataset are still about 0.35.
How can I train a lower bit rate model on Kodak dataset?
Thanks!

**Comment by fab-jul** [comment]
One thing you can try is set `num_chan_bn` to a lower value, such as `num_chan_bn = 16`. Note however that `H_target` only roughly upper bounds the bitrate on the training set, the actual bitrate will vary from testset to testset.

**Comment by FanYanqi** [comment]
Sorry for reply late. As you've said, I set `num_chan_bn = 8, H_target = 2*0.10` and trained a model test on Kodak with bpp: 0.152 and ms-ssim: 0.939. Thanks for your reply.
