### ISSUE TITLE
How to optimize with mse?

### ISSUE THREAD

**Issue by hyeseojy** [fab-jul/imgcomp-cvpr#31]
Hello
I don't know if it still solves the issue related to the code, but I'll share it with you.

I would like to optimize the code you provided to me in mse.

I thought
"imgcomp-cvpr/code/ae_configs/cvpr/base
distortion_to_minimize=ms_ssim
-> distortion_to_minimize=mse" to optimize to mse.

However, the above method causes the following error.
For your information, there is nothing fixed except a distortion (ms-ssim optimization did a good job).

<img width="599" alt="error" src="https://user-images.githubusercontent.com/75883475/118921939-0e2b5d80-b974-11eb-9207-7d1f23b33a6e.png">

I tried to solve it by myself, but I'm a beginner, so I don't know how to solve it.
Thank you for sharing such a wonderful code. I'd appreciate it if you could help me with my problem.

Thank you :)

**Comment by fab-jul** [comment]
Can you should the full error stack trace?

**Comment by hyeseojy** [comment]
Thanks for your reply.
The full error stack trace is like this picture.

<img width="690" alt="error_2" src="https://user-images.githubusercontent.com/75883475/118977323-fb834980-b9b0-11eb-888e-385fd10e3c59.png">

**Comment by hyeseojy** [comment]
By the way, is it right to do
"imgcomp-cvpr/code/ae_configs/cvpr/base
distortion_to_minimize=ms_ssim
-> distortion_to_minimize=mse" to optimize with mse?

**Comment by hyeseojy** [comment]
> Hello
> I don't know if it still solves the issue related to the code, but I'll share it with you.
> 
> I would like to optimize the code you provided to me in mse.
> 
> I thought
> "imgcomp-cvpr/code/ae_configs/cvpr/base
> distortion_to_minimize=ms_ssim
> -> distortion_to_minimize=mse" to optimize to mse.
> 
> However, the above method causes the following error.
> For your information, there is nothing fixed except a distortion (ms-ssim optimization did a good job).
> 
> <img alt="error" width="599" src="https://user-images.githubusercontent.com/75883475/118921939-0e2b5d80-b974-11eb-9207-7d1f23b33a6e.png">
> 
> I tried to solve it by myself, but I'm a beginner, so I don't know how to solve it.
> Thank you for sharing such a wonderful code. I'd appreciate it if you could help me with my problem.
> 
> Thank you :)
