### ISSUE TITLE
Download link/ pretrained models

### ISSUE THREAD

**Issue by Nikolai10** [fab-jul/imgcomp-cvpr#33]
Hello @fab-jul, 

the download link seems to no longer work (https://data.vision.ee.ethz.ch/mentzerf/imgcomp-ckpts/ckpts.tar.gz). Is there any other way to get the checkpoints?

Thank you very much.

**Comment by Nikolai10** [comment]
seemed to be only a temporary issue.

**Comment by fab-jul** [comment]
Yeah the data was temporarily deleted, thanks for reporting! There was a backup luckily.
