### ISSUE TITLE
restore

### ISSUE THREAD

**Issue by wensihan** [fab-jul/imgcomp-cvpr#5]
Hello, when I using the argument of --restore, there is something wrong:
OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_input_glob__data_wency_CLIC_mobile_train__.png/shuffle_batch_join/random_shuffle_queue' is closed and has insufficient elements (requested 30, current size 0)

Can you give me some advice? Thank you~

**Comment by fab-jul** [comment]
Make sure there is data where you point the test queue. It looks like there are no images.
